# printf "%-15s %-20s %-10s %-10s %-10s %-10s %-10s %-15s %-10s %-20s %-10s %-10s\n" "Component" "Specifications" "Internal" "Predicates" "Proof" "Loops" "Globals" "Linux Models" "Total" "Syntax-only" "Total%" "Proof-to-code%"

# As reported in https://dl.acm.org/doi/pdf/10.1145/3571194. Bottom of page 26.
CODE=96

# CN

CN_COUNT_FILES="cn/early_alloc.c cn/memory.h cn/cn_predicates.h"

CN_SPECIFICATIONS=$(grep -E 'SPECS' $CN_COUNT_FILES | wc -l)
CN_INTERNAL=$(grep -E -- 'INTERNAL' $CN_COUNT_FILES | wc -l)
CN_PREDICATES=$(grep -E 'PREDICATES' $CN_COUNT_FILES | wc -l)
CN_PROOF=$(grep -E 'PROOF' $CN_COUNT_FILES | wc -l)
CN_LOOPS=$(grep -E 'LOOPINV' $CN_COUNT_FILES | wc -l)
CN_GLOBALS=$(grep -E 'GLOBAL' $CN_COUNT_FILES | wc -l)
CN_LINUX_MODELS=$(grep -E 'LINUX_MODELS' $CN_COUNT_FILES | wc -l)

CN_TOTAL=$((CN_SPECIFICATIONS + CN_INTERNAL + CN_PREDICATES + CN_PROOF + CN_LOOPS + CN_GLOBALS + CN_LINUX_MODELS))

CN_SYNTAX=$(grep -E 'SYNTAX' $CN_COUNT_FILES | wc -l)

printf "%-15s %-20s %-10s %-10s %-10s %-10s %-10s %-15s %-10s %-20s %-10s %-10s\n" "CN" "$CN_SPECIFICATIONS" "$CN_INTERNAL" "$CN_PREDICATES" "$CN_PROOF" "$CN_LOOPS" "$CN_GLOBALS" "$CN_LINUX_MODELS" "$CN_TOTAL" "$CN_SYNTAX" "$(echo "scale=2; $CN_TOTAL * 100 / $CODE" | bc)" "$(echo "scale=2; ($CN_TOTAL - $CN_SYNTAX) * 100 / $CODE" | bc)"

# Verifast


VERIFAST_COUNT_FILES="verifast/early_alloc.c verifast/memory.h verifast/verifast_predicates.h verifast/lemmas.h"

VERIFAST_SPECIFICATIONS=$(grep -E 'SPECS' $VERIFAST_COUNT_FILES | wc -l)
VERIFAST_INTERNAL=$(grep -E -- 'INTERNAL' $VERIFAST_COUNT_FILES | wc -l)
VERIFAST_PREDICATES=$(grep -E 'PREDICATES' $VERIFAST_COUNT_FILES | wc -l)
VERIFAST_PROOF=$(grep -E 'PROOF' $VERIFAST_COUNT_FILES | wc -l)
VERIFAST_LOOPS=$(grep -E 'LOOPINV' $VERIFAST_COUNT_FILES | wc -l)
VERIFAST_GLOBALS=$(grep -E 'GLOBAL' $VERIFAST_COUNT_FILES | wc -l)
VERIFAST_LINUX_MODELS=$(grep -E 'LINUX_MODELS' $VERIFAST_COUNT_FILES | wc -l)

VERIFAST_TOTAL=$((VERIFAST_SPECIFICATIONS + VERIFAST_INTERNAL + VERIFAST_PREDICATES + VERIFAST_PROOF + VERIFAST_LOOPS + VERIFAST_GLOBALS + VERIFAST_LINUX_MODELS))

VERIFAST_SYNTAX=$(grep -E 'SYNTAX' $VERIFAST_COUNT_FILES | wc -l)

printf "%-15s %-20s %-10s %-10s %-10s %-10s %-10s %-15s %-10s %-20s %-10s %-10s\n" "Verifast" "$VERIFAST_SPECIFICATIONS" "$VERIFAST_INTERNAL" "$VERIFAST_PREDICATES" "$VERIFAST_PROOF" "$VERIFAST_LOOPS" "$VERIFAST_GLOBALS" "$VERIFAST_LINUX_MODELS" "$VERIFAST_TOTAL" "$VERIFAST_SYNTAX" "$(echo "scale=2; $VERIFAST_TOTAL * 100 / $CODE" | bc)" "$(echo "scale=2; ($VERIFAST_TOTAL - $VERIFAST_SYNTAX) * 100 / $CODE" | bc)"

# TPOT

TPOT_COUNT_FILES="tpot/specs.c original/early_alloc.c"

TPOT_SPECIFICATIONS=$(grep -E 'SPECS' $TPOT_COUNT_FILES | wc -l)
TPOT_INTERNAL=$(grep -E -- 'INTERNAL' $TPOT_COUNT_FILES | wc -l)
TPOT_PREDICATES=$(grep -E 'PREDICATES' $TPOT_COUNT_FILES | wc -l)
TPOT_PROOF=$(grep -E 'PROOF' $TPOT_COUNT_FILES | wc -l)
TPOT_LOOPS=$(grep -E 'LOOPINV' $TPOT_COUNT_FILES | wc -l)
TPOT_GLOBALS=$(grep -E 'GLOBAL' $TPOT_COUNT_FILES | wc -l)
TPOT_LINUX_MODELS=$(grep -E 'LINUX_MODELS' $TPOT_COUNT_FILES | wc -l)

TPOT_TOTAL=$((TPOT_SPECIFICATIONS + TPOT_INTERNAL + TPOT_PREDICATES + TPOT_PROOF + TPOT_LOOPS + TPOT_GLOBALS + TPOT_LINUX_MODELS))

TPOT_SYNTAX=$(grep -E 'SYNTAX' $TPOT_COUNT_FILES | wc -l)

printf "%-15s %-20s %-10s %-10s %-10s %-10s %-10s %-15s %-10s %-20s %-10s %-10s\n" "TPot" "$TPOT_SPECIFICATIONS" "$TPOT_INTERNAL" "$TPOT_PREDICATES" "$TPOT_PROOF" "$TPOT_LOOPS" "$TPOT_GLOBALS" "$TPOT_LINUX_MODELS" "$TPOT_TOTAL" "$TPOT_SYNTAX" "$(echo "scale=2; $TPOT_TOTAL * 100 / $CODE" | bc)" "$(echo "scale=2; ($TPOT_TOTAL - $TPOT_SYNTAX) * 100 / $CODE" | bc)"
